@startuml packages_domain_events
set namespaceSeparator none
package "apex.src.domain.events" as apex.src.domain.events {
}
package "apex.src.domain.events.domain_events" as apex.src.domain.events.domain_events {
}
package "apex.src.domain.events.event_types" as apex.src.domain.events.event_types {
}
package "apex.src.domain.events.priority_event_bus" as apex.src.domain.events.priority_event_bus {
}
apex.src.domain.events --> apex.src.domain.events.domain_events
apex.src.domain.events --> apex.src.domain.events.event_types
apex.src.domain.events --> apex.src.domain.events.priority_event_bus
apex.src.domain.events.event_types --> apex.src.domain.events.domain_events
apex.src.domain.events.priority_event_bus --> apex.src.domain.events.event_types
@enduml
