@startuml packages_application_orchestrator
set namespaceSeparator none
package "apex.src.application.orchestrator" as apex.src.application.orchestrator {
}
package "apex.src.application.orchestrator.data_coordinator" as apex.src.application.orchestrator.data_coordinator {
}
package "apex.src.application.orchestrator.orchestrator" as apex.src.application.orchestrator.orchestrator {
}
package "apex.src.application.orchestrator.shutdown" as apex.src.application.orchestrator.shutdown {
}
package "apex.src.application.orchestrator.signal_coordinator" as apex.src.application.orchestrator.signal_coordinator {
}
package "apex.src.application.orchestrator.signal_pipeline" as apex.src.application.orchestrator.signal_pipeline {
}
package "apex.src.application.orchestrator.signal_pipeline.bar_preloader" as apex.src.application.orchestrator.signal_pipeline.bar_preloader {
}
package "apex.src.application.orchestrator.snapshot_coordinator" as apex.src.application.orchestrator.snapshot_coordinator {
}
apex.src.application.orchestrator --> apex.src.application.orchestrator
apex.src.application.orchestrator --> apex.src.application.orchestrator.data_coordinator
apex.src.application.orchestrator --> apex.src.application.orchestrator.shutdown
apex.src.application.orchestrator --> apex.src.application.orchestrator.snapshot_coordinator
apex.src.application.orchestrator.orchestrator --> apex.src.application.orchestrator.data_coordinator
apex.src.application.orchestrator.orchestrator --> apex.src.application.orchestrator.signal_coordinator
apex.src.application.orchestrator.orchestrator --> apex.src.application.orchestrator.snapshot_coordinator
apex.src.application.orchestrator.signal_coordinator --> apex.src.application.orchestrator.signal_pipeline
apex.src.application.orchestrator.signal_pipeline --> apex.src.application.orchestrator.signal_pipeline.bar_preloader
@enduml
