"""
Pre-built rules for pattern indicators.

Includes rules for:
- Candlestick: Pattern detection signals
- Support/Resistance: Level proximity and breakouts
- Trendline: Trend direction changes
- Pivot: Pivot point breakouts
- Fibonacci: Retracement level touches
"""

from ..models import (
    ConditionType,
    SignalCategory,
    SignalDirection,
    SignalPriority,
    SignalRule,
)

PATTERN_RULES = [
    # =========================================================================
    # Candlestick Pattern Rules
    # =========================================================================
    SignalRule(
        name="candlestick_bullish_pattern",
        indicator="candlestick",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.BUY,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "strongest_signal",
            "from": ["neutral", "bearish"],
            "to": ["bullish"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} bullish candlestick pattern detected",
    ),
    SignalRule(
        name="candlestick_bearish_pattern",
        indicator="candlestick",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.SELL,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "strongest_signal",
            "from": ["neutral", "bullish"],
            "to": ["bearish"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} bearish candlestick pattern detected",
    ),
    # =========================================================================
    # Support/Resistance Rules
    # =========================================================================
    SignalRule(
        name="sr_approaching_support",
        indicator="support_resistance",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.ALERT,
        strength=65,
        priority=SignalPriority.MEDIUM,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["between", "above_support", "below_resistance", "outside"],
            "to": ["at_support"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} approaching key support level",
    ),
    SignalRule(
        name="sr_approaching_resistance",
        indicator="support_resistance",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.ALERT,
        strength=65,
        priority=SignalPriority.MEDIUM,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["between", "above_support", "below_resistance", "outside"],
            "to": ["at_resistance"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} approaching key resistance level",
    ),
    SignalRule(
        name="sr_support_bounce",
        indicator="support_resistance",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.BUY,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["at_support"],
            "to": ["between", "above_support"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} bounced off support level (bullish)",
    ),
    SignalRule(
        name="sr_resistance_rejection",
        indicator="support_resistance",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.SELL,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["at_resistance"],
            "to": ["between", "below_resistance"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} rejected at resistance level (bearish)",
    ),
    # =========================================================================
    # Trendline Rules
    # =========================================================================
    SignalRule(
        name="trendline_uptrend_start",
        indicator="trendline",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.BUY,
        strength=65,
        priority=SignalPriority.MEDIUM,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "trend",
            "from": ["sideways", "downtrend"],
            "to": ["uptrend"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} trendline indicates uptrend starting",
    ),
    SignalRule(
        name="trendline_downtrend_start",
        indicator="trendline",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.SELL,
        strength=65,
        priority=SignalPriority.MEDIUM,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "trend",
            "from": ["sideways", "uptrend"],
            "to": ["downtrend"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} trendline indicates downtrend starting",
    ),
    SignalRule(
        name="trendline_consolidation",
        indicator="trendline",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.ALERT,
        strength=55,
        priority=SignalPriority.LOW,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "trend",
            "from": ["uptrend", "downtrend"],
            "to": ["sideways"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} entering consolidation (sideways trend)",
    ),
    # =========================================================================
    # Pivot Points Rules
    # =========================================================================
    SignalRule(
        name="pivot_bullish_breakout",
        indicator="pivot",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.BUY,
        strength=65,
        priority=SignalPriority.MEDIUM,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["below_pivot", "at_pivot", "neutral"],
            "to": ["above_pivot", "at_r2", "at_r3", "above_r3"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} broke above pivot point (bullish)",
    ),
    SignalRule(
        name="pivot_bearish_breakdown",
        indicator="pivot",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.SELL,
        strength=65,
        priority=SignalPriority.MEDIUM,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["above_pivot", "at_pivot", "neutral"],
            "to": ["below_pivot", "at_s1", "at_s2", "below_s3"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} broke below pivot point (bearish)",
    ),
    SignalRule(
        name="pivot_r2_test",
        indicator="pivot",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.ALERT,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["above_pivot", "at_pivot"],
            "to": ["at_r2", "at_r3"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} testing R2/R3 resistance",
    ),
    SignalRule(
        name="pivot_s2_test",
        indicator="pivot",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.ALERT,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["below_pivot", "at_pivot"],
            "to": ["at_s2", "below_s3"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} testing S2/S3 support",
    ),
    # =========================================================================
    # Fibonacci Rules
    # =========================================================================
    SignalRule(
        name="fib_at_382",
        indicator="fibonacci",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.ALERT,
        strength=65,
        priority=SignalPriority.MEDIUM,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["between", "outside", "above_range", "below_range"],
            "to": ["at_0.382"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} at 38.2% Fibonacci retracement level",
    ),
    SignalRule(
        name="fib_at_500",
        indicator="fibonacci",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.ALERT,
        strength=65,
        priority=SignalPriority.MEDIUM,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["between", "outside", "above_range", "below_range"],
            "to": ["at_0.5"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} at 50% Fibonacci retracement level",
    ),
    SignalRule(
        name="fib_at_618",
        indicator="fibonacci",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.ALERT,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["between", "outside", "above_range", "below_range"],
            "to": ["at_0.618"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=7200,
        message_template="{symbol} at 61.8% Golden Ratio Fibonacci level",
    ),
    SignalRule(
        name="fib_breakout_above",
        indicator="fibonacci",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.BUY,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["between", "at_0.786", "at_1.0"],
            "to": ["above_range"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} broke above Fibonacci range (bullish breakout)",
    ),
    SignalRule(
        name="fib_breakdown_below",
        indicator="fibonacci",
        category=SignalCategory.PATTERN,
        direction=SignalDirection.SELL,
        strength=70,
        priority=SignalPriority.HIGH,
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={
            "field": "position",
            "from": ["between", "at_0.236", "at_0.0"],
            "to": ["below_range"],
        },
        timeframes=("1h", "4h", "1d"),
        cooldown_seconds=14400,
        message_template="{symbol} broke below Fibonacci range (bearish breakdown)",
    ),
]
