# Moving Average Cross Strategy Configuration

strategy:
  name: "MovingAverageCross"
  parameters:
    fast_period: 20
    slow_period: 50
    
position_sizing:
  method: "fixed"
  size: 0.95  # Use 95% of available capital
  
risk_management:
  stop_loss: 0.02  # 2% stop loss
  take_profit: 0.05  # 5% take profit
