"""
Email-friendly heatmap renderer.

Renders summary.json as static HTML for email body.
No JavaScript, no interactivity - pure informational content.

IMPORTANT: Reuses constants from heatmap/model.py (Single Source of Truth).
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.infrastructure.reporting.heatmap.etf_dashboard import REGIME_NAMES
from src.infrastructure.reporting.heatmap.extractors import extract_regime

# REUSE existing constants - NO DUPLICATION
from src.infrastructure.reporting.heatmap.model import (
    ETF_CONFIG,
    MARKET_ETFS,
)
from src.infrastructure.reporting.regime.utils import REGIME_COLORS, get_theme_colors


def render_email_html(summary_path: str | Path) -> str:
    """
    Render summary.json as email-friendly HTML.

    Args:
        summary_path: Path to the summary.json file generated by signal pipeline.

    Returns:
        HTML string suitable for email body (no JS, inline styles).
    """
    summary_data = json.loads(Path(summary_path).read_text())
    tickers = {t["symbol"]: t for t in summary_data.get("tickers", [])}

    # Use imported constants (Single Source of Truth)
    sector_symbols = list(ETF_CONFIG["sectors"]["symbols"])

    # Build market ETF cards (using MARKET_ETFS from model.py)
    market_html = _render_etf_row(tickers, MARKET_ETFS)

    # Build sector ETF cards (using sector list from ETF_CONFIG)
    sector_html = _render_etf_row(tickers, sector_symbols)

    # Build regime distribution
    regime_dist = _count_regimes(summary_data)
    regime_html = _render_regime_distribution(regime_dist)

    # Generate timestamp
    generated_at = summary_data.get("generated_at")
    if generated_at:
        # Format for display
        try:
            dt = datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
            timestamp_str = dt.strftime("%b %d, %Y %I:%M %p ET")
        except (ValueError, AttributeError):
            timestamp_str = generated_at
    else:
        timestamp_str = datetime.now().strftime("%b %d, %Y %I:%M %p")

    # Get theme colors from existing utility
    colors = get_theme_colors("dark")

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: {colors["bg"]};
            color: {colors["text"]};
            padding: 20px;
            margin: 0;
            line-height: 1.5;
        }}
        .container {{
            max-width: 600px;
            margin: 0 auto;
        }}
        .header {{
            text-align: center;
            margin-bottom: 24px;
            padding-bottom: 16px;
            border-bottom: 1px solid {colors["border"]};
        }}
        .header h2 {{
            margin: 0 0 8px 0;
            font-size: 24px;
            font-weight: 600;
        }}
        .header .timestamp {{
            color: {colors["text_muted"]};
            font-size: 14px;
        }}
        .section {{
            background: {colors["card_bg"]};
            border-radius: 8px;
            padding: 16px;
            margin-bottom: 16px;
        }}
        .section-title {{
            font-size: 12px;
            font-weight: 600;
            color: {colors["text_muted"]};
            margin-bottom: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}
        .etf-grid {{
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
        }}
        .etf-card {{
            background: {colors["bg"]};
            border-radius: 6px;
            padding: 10px 12px;
            min-width: 65px;
            text-align: center;
        }}
        .etf-symbol {{
            font-weight: 600;
            font-size: 13px;
            margin-bottom: 4px;
        }}
        .etf-regime {{
            font-size: 11px;
            padding: 2px 6px;
            border-radius: 4px;
            display: inline-block;
            font-weight: 500;
        }}
        .etf-change {{
            font-size: 11px;
            color: {colors["text_muted"]};
            margin-top: 4px;
        }}
        .regime-row {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
            border-bottom: 1px solid {colors["border"]};
        }}
        .regime-row:last-child {{
            border-bottom: none;
        }}
        .regime-indicator {{
            display: inline-block;
            width: 10px;
            height: 10px;
            border-radius: 50%;
            margin-right: 8px;
        }}
        .regime-label {{
            font-size: 14px;
        }}
        .regime-count {{
            font-size: 14px;
            color: {colors["text_muted"]};
        }}
        .footer {{
            text-align: center;
            margin-top: 24px;
            padding-top: 16px;
            border-top: 1px solid {colors["border"]};
        }}
        .footer a {{
            color: #60a5fa;
            text-decoration: none;
            font-size: 14px;
        }}
        .footer a:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>APEX Signal Report</h2>
            <div class="timestamp">{timestamp_str}</div>
        </div>

        <div class="section">
            <div class="section-title">Market Overview</div>
            <div class="etf-grid">{market_html}</div>
        </div>

        <div class="section">
            <div class="section-title">Sectors</div>
            <div class="etf-grid">{sector_html}</div>
        </div>

        <div class="section">
            <div class="section-title">Regime Distribution</div>
            {regime_html}
        </div>

        <div class="footer">
            <a href="https://moremeds.github.io/apex/">View Full Interactive Report &rarr;</a>
        </div>
    </div>
</body>
</html>"""


def _render_etf_row(tickers: Dict[str, Any], symbols: List[str]) -> str:
    """Render a row of ETF cards using imported extractors."""
    cards = []
    for symbol in symbols:
        ticker = tickers.get(symbol, {})
        # Use imported extract_regime() function
        regime = extract_regime(ticker)
        change = ticker.get("daily_change_pct")
        # Use imported REGIME_COLORS dict (has bg/text/name)
        default_regime_info = {"bg": "#64748b", "text": "#ffffff", "name": "Unknown"}
        regime_info = (
            REGIME_COLORS.get(regime, default_regime_info) if regime else default_regime_info
        )
        change_str = f"{change:+.1f}%" if change is not None else ""

        cards.append(f"""
            <div class="etf-card">
                <div class="etf-symbol">{symbol}</div>
                <div class="etf-regime" style="background: {regime_info['bg']}; color: {regime_info['text']};">{regime or "—"}</div>
                <div class="etf-change">{change_str}</div>
            </div>""")
    return "".join(cards)


def _count_regimes(summary: Dict[str, Any]) -> Dict[str, int]:
    """Count stocks by regime using imported extractor."""
    counts: Dict[str, int] = {"R0": 0, "R1": 0, "R2": 0, "R3": 0}
    for ticker in summary.get("tickers", []):
        regime = extract_regime(ticker)  # Reuse imported function
        if regime in counts:
            counts[regime] += 1
    return counts


def _render_regime_distribution(dist: Dict[str, int]) -> str:
    """Render regime distribution rows using imported constants."""
    total = sum(dist.values()) or 1
    rows = []
    for regime, count in dist.items():
        # Use imported REGIME_NAMES and REGIME_COLORS
        name = REGIME_NAMES.get(regime, regime)
        regime_info = REGIME_COLORS.get(regime, {"bg": "#64748b"})
        pct = (count / total) * 100
        rows.append(f"""
            <div class="regime-row">
                <span class="regime-label">
                    <span class="regime-indicator" style="background: {regime_info['bg']};"></span>
                    {name}
                </span>
                <span class="regime-count">{count} stocks ({pct:.0f}%)</span>
            </div>""")
    return "".join(rows)
