# Default Configuration for Apex Backtesting

data:
  cache_dir: "~/.apex/cache"
  quality_threshold: 0.7
  
engine:
  initial_cash: 100000
  commission: 0.001
  slippage: 0.001
  
logging:
  level: "INFO"
  file: "logs/apex.log"
